idf_component_register(
    SRCS
        "src/esp_file_transfer.c"
        "src/esp_file_transfer_sender.c"
        "src/esp_file_transfer_receiver.c"
        "src/esp_file_transfer_protocol.c"
        "src/esp_file_transfer_gmp.c"
        "src/esp_file_transfer_data.c"
        "src/esp_file_transfer_fs.c"
        "src/esp_file_transfer_hash.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "private_include"
    REQUIRES
        esp_gmp
    PRIV_REQUIRES
        esp_timer
        freertos
        mbedtls
)
